### ISSUE TITLE
Utteranc.es comment widget broken

### ISSUE THREAD

**Issue by dandv** [julian-west/julian-west#1]
Hey, I tried to leave a comment on your excellent guide on [setting up macOS for DS](https://engineeringfordatascience.com/posts/setting_up_a_macbook_for_data_science/) but ran into this error:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/33569/236922041-b55e25a5-6f2f-4ffd-8e98-83bc5cd276ed.png">

**Comment by julian-west** [comment]
@dandv thanks for highlighting. I've reinstalled the Utterances app -- hopefully it is working now 🤞
